[tool.poetry]
name = "projeto-teste"
version = "0.1.0"
description = "\"\""
authors = ["Leonardo José <leojdsc99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
